# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Xavier Coadic
email: xcoadic@gmail.com
description: Explorer des champs, Faire des cultures {Simplexité parfois}
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://xavcc.github.io" # the base hostname & protocol for your site
twitter_username: XavierCoadic
github_username:  XavCC
mastodon_username: XavCC
paginate: 5

gems: [jekyll-paginate, kramdown]
# Build settings
markdown: kramdown

# Typography
# To use, publish a kit and enter the ID here. If you do not wish to use Typekit,
# leave this ID blank
typekit_kit_id: kwf5dox
